sudo: false
dist: trusty
language: node_js

branches:
  only:
    - master
    - next

cache:
  yarn: true

matrix:
  include:
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART=Compiler-caching.test.js Compiler.test.js
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART=ConfigTestCases.test.js Errors.test.js
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART=Examples.test.js HotModuleReplacementPlugin.test.js
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART=HotTestCases.test.js Integration.test.js
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART=MultiCompiler.test.js NodeTemplatePlugin.test.js
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART=Stats.test.js StatsTestCases.test.js
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART=TestCasesAllCombined.test.js TestCasesDevelopment.test.js
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART=TestCasesDevtoolCheapEvalModuleSourceMap.test.js TestCasesDevtoolCheapEvalSourceMap.test.js
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART=TestCasesDevtoolCheapInlineSourceMap.test.js TestCasesDevtoolCheapSourceMap.test.js
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART=TestCasesDevtoolEval.test.js TestCasesDevtoolEvalNamedModules.test.js
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART=TestCasesDevtoolEvalSourceMap.test.js TestCasesDevtoolInlineSourceMap.test.js
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART=TestCasesDevtoolSourceMap.test.js TestCasesHot.test.js
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART=TestCasesHotMultiStep.test.js TestCasesMinimizedHashedModules.test.js
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART=TestCasesMinimizedSourceMap.test.js TestCasesNormal.test.js
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART=TestCasesProduction.test.js Validation.test.js
  allow_failures:
    - os: osx
  fast_finish: true

install:
  - yarn --frozen-lockfile
  - yarn link --frozen-lockfile || true
  - yarn link webpack --frozen-lockfile

script:
  - yarn cover:init
  - yarn cover:single --ci $JEST $JOB_PART
  - yarn cover:report-min

after_success:
  - cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose
  - bash <(curl -s https://codecov.io/bash) -F $JOB_PART -X gcov
  - rm -rf ./coverage

notifications:
  slack:
    secure: JduSdKWwbnLCwo7Z4E59SGE+Uw832UwnXzQiKEpg1BV45MYDPRiGltly1tRHmPh9OGjvGx3XSkC2tNGOBLtL4UL2SCkf012x0t7jDutKRfcv/njynl8jk8l+UhPmaWiHXDQAgGiiKdL4RfzPLW3HeVHCOWm0LKMzcarTa8tw+rE=
