sudo: false
dist: trusty
language: node_js

branches:
  only:
    - master
    - next

cache:
  yarn: true

matrix:
  include:
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="ConfigTestCases.test.js|Stats.test.js"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="ConfigTestCases.test.js|Stats.test.js -t additional-pass|async-commons-chunk|code-generation|commons-chunk-plugin"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="ConfigTestCases.test.js|Stats.test.js -t compiletime|context-exclusion|context-replacement|custom-hash-function"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="ConfigTestCases.test.js|Stats.test.js -t defaulter|delegated|delegated-hash|devtools"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="ConfigTestCases.test.js|Stats.test.js -t dll-plugin|entry|errors|externals"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="ConfigTestCases.test.js|Stats.test.js -t filename-template|hash-length|ignore|issues"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="ConfigTestCases.test.js|Stats.test.js -t library|loaders|module-name|no-parse"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="ConfigTestCases.test.js|Stats.test.js -t output|parsing|performance|plugins"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="ConfigTestCases.test.js|Stats.test.js -t race-conditions|records|rule-set|runtime"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="ConfigTestCases.test.js|Stats.test.js -t scope-hoisting|side-effects|simple|source-map"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="ConfigTestCases.test.js|Stats.test.js -t split-chunks|target|web"
  allow_failures:
    - os: osx
  fast_finish: true

install:
  - yarn --frozen-lockfile
  - yarn link --frozen-lockfile || true
  - yarn link webpack --frozen-lockfile

script:
  - yarn cover:init
  - yarn cover:single --ci $JEST $JOB_PART
  - yarn cover:report-min

after_success:
  - cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose
  - bash <(curl -s https://codecov.io/bash) -F $JOB_PART -X gcov
  - rm -rf ./coverage

notifications:
  slack:
    secure: JduSdKWwbnLCwo7Z4E59SGE+Uw832UwnXzQiKEpg1BV45MYDPRiGltly1tRHmPh9OGjvGx3XSkC2tNGOBLtL4UL2SCkf012x0t7jDutKRfcv/njynl8jk8l+UhPmaWiHXDQAgGiiKdL4RfzPLW3HeVHCOWm0LKMzcarTa8tw+rE=
