sudo: false
dist: trusty
language: node_js

branches:
  only:
    - master
    - next

cache:
  yarn: true

matrix:
  include:
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="--testMatch <rootDir>/test/*.test.js"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="ConfigTestCases.test.js|Stats.test.js"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="ConfigTestCases.test.js|Stats.test.js"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="ConfigTestCases.test.js|Stats.test.js"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="ConfigTestCases.test.js|Stats.test.js"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="ConfigTestCases.test.js|Stats.test.js"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="Compiler-caching.test.js|Compiler.test.js|ConfigTestCases.test.js|Errors.test.js"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="Errors.test.js|Examples.test.js|HotModuleReplacementPlugin.test.js"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="HotModuleReplacementPlugin.test.js|HotTestCases.test.js|Integration.test.js"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="Integration.test.js|MultiCompiler.test.js|NodeTemplatePlugin.test.js"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="NodeTemplatePlugin.test.js|Stats.test.js|StatsTestCases.test.js"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="StatsTestCases.test.js|TestCasesAllCombined.test.js|TestCasesDevelopment.test.js"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="TestCasesDevelopment.test.js|TestCasesDevtoolCheapEvalModuleSourceMap.test.js|TestCasesDevtoolCheapEvalSourceMap.test.js"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="TestCasesDevtoolCheapEvalSourceMap.test.js|TestCasesDevtoolCheapInlineSourceMap.test.js|TestCasesDevtoolCheapSourceMap.test.js"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="TestCasesDevtoolCheapSourceMap.test.js|TestCasesDevtoolEval.test.js|TestCasesDevtoolEvalNamedModules.test.js"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="TestCasesDevtoolEvalNamedModules.test.js|TestCasesDevtoolEvalSourceMap.test.js|TestCasesDevtoolInlineSourceMap.test.js"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="TestCasesDevtoolInlineSourceMap.test.js|TestCasesDevtoolSourceMap.test.js|TestCasesHot.test.js"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="TestCasesHot.test.js|TestCasesHotMultiStep.test.js|TestCasesMinimizedHashedModules.test.js"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="TestCasesMinimizedHashedModules.test.js|TestCasesMinimizedSourceMap.test.js|TestCasesNormal.test.js"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="TestCasesNormal.test.js|TestCasesProduction.test.js|Validation.test.js"
  allow_failures:
    - os: osx
  fast_finish: true

install:
  - yarn --frozen-lockfile
  - yarn link --frozen-lockfile || true
  - yarn link webpack --frozen-lockfile

script:
  - yarn cover:init
  - yarn cover:single --ci $JEST $JOB_PART
  - yarn cover:report-min

notifications:
  slack:
    secure: JduSdKWwbnLCwo7Z4E59SGE+Uw832UwnXzQiKEpg1BV45MYDPRiGltly1tRHmPh9OGjvGx3XSkC2tNGOBLtL4UL2SCkf012x0t7jDutKRfcv/njynl8jk8l+UhPmaWiHXDQAgGiiKdL4RfzPLW3HeVHCOWm0LKMzcarTa8tw+rE=
