sudo: false
dist: trusty
language: node_js

branches:
  only:
    - master
    - next

cache:
  yarn: true

matrix:
  include:
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="integration1"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="integration1"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="integration1"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="integration1"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="integration1"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="integration2"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="integration2"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="integration2"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="integration2"
    - os: linux
      node_js: "10"
      env: NO_WATCH_TESTS=1 JEST=--maxWorkers=2 JOB_PART="integration2"
  allow_failures:
    - os: osx
  fast_finish: true

install:
  - yarn --frozen-lockfile
  - yarn link --frozen-lockfile || true
  - yarn link webpack --frozen-lockfile

script:
  - yarn cover:init
  - yarn cover:$JOB_PART --ci $JEST
  - yarn cover:report-min

notifications:
  slack:
    secure: JduSdKWwbnLCwo7Z4E59SGE+Uw832UwnXzQiKEpg1BV45MYDPRiGltly1tRHmPh9OGjvGx3XSkC2tNGOBLtL4UL2SCkf012x0t7jDutKRfcv/njynl8jk8l+UhPmaWiHXDQAgGiiKdL4RfzPLW3HeVHCOWm0LKMzcarTa8tw+rE=
